controllers:
    resource: ../src/Controller/
    type: attribute

ObjectifsController:
    path : /objectifs
    controller: App\Controller\ObjectifsController::objectifs

TaskController_new:
    path : /task/new
    controller: App\Controller\TaskController::new #on appelle la fonction créer

FriendsController:
    path : /friends
    controller: App\Controller\FriendsController::friends
