controllers:
    resource: ../src/Controller/
    type: attribute

ObjectifsController:
    path : /objectifs
    controller: App\Controller\ObjectifsController::objectifs

FriendsController:
    path : /friends
    controller: App\Controller\FriendsController::friends
